.\" $Id: gespeaker.1 0.7 2009-12-06 14:12 muflone $
.\"
.\" Copyright (c) 2009 Fabio Castelli

.TH GESPEAKER "1" "December 06, 2009"

.SH NAME
.B Gespeaker
\- A GTK+ frontend for eSpeak and mbrola

.SH SYNOPSIS
gespeaker

.SH DESCRIPTION
.PP
.B Gespeaker
is a GTK+ frontend for eSpeak and mbrola.
It allows to play a text in many languages with settings  for voice, pitch,
volume, speed and word gap.

.PP
Since version 0.6 it can use mbrola package and voices to
obtain a more realistic text reading experience.

.PP
If mbrola was installed then the voices path must be selected from the mbrola 
voices tab on the preferences page.

.SH FILES
Personal settings will be kept under ~/.gespeaker

.SH AUTHORS
.B Gespeaker
was written by Fabio Castelli <muflone@vbsimple.net>

.SH HOMEPAGE
International project: http://code.google.com/p/gespeaker/

Italian project: http://ubuntrucchi.wordpress.com/progetti-projects/gespeaker/

